### ISSUE TITLE
Connectivity Loss & Safety

### ISSUE THREAD

**Issue by juliavankirk** [DIT112-V21/group-07#3]
**User Story:** 
As a driver I want my vehicle to slow down and park in a safe place when the MQTT connection from the server to the app has been lost in an unexpected way, in order to avoid being involved in or causing any accidents.

**Acceptance Criteria:**
3.1 The vehicle should slow down and park* when the MQTT connection from the app to the server is disconnected ungracefully (without disconnect message).
3.2 The vehicle should slow down and and *move to the right hand side of the "road" in order to park safely, if it is safe to do so.
3.3 The vehicle should set to "park" once it has moved off the "road".

**Comment by juliavankirk** [comment]
> 3.2 The vehicle should slow down and and move to the right hand side of the "road" in order to park safely.

How do we avoid hitting people/ objects as we park onto the curb?  If we're relying on sensors but have no knowledge of position, how do we know when we've reached the curb?

**Comment by ChrisAxt** [comment]
> > 3.2 The vehicle should slow down and and move to the right hand side of the "road" in order to park safely.
> 
> How do we avoid hitting people/ objects as we park onto the curb? If we're relying on sensors but have no knowledge of position, how do we know when we've reached the curb?

The vehicle is instructed to perform a predetermined maneuver but will still retain all of the avoidance capabilities. Unfortunately due to our environment finding a curb (which would most likely be a wall/hill) would take us so far off track that it wouldn't be perceived as pulling over (It might need to travel to the opposite side of the map to find a "curb").
