### ISSUE TITLE
[BUG] Motion Accuracy

### ISSUE THREAD

**Issue by juliavankirk** [DIT112-V21/group-07#58]
The car currently jumps from one state to another, as there isn't a way to handle delta in speed and angle.

Suggested fix:
- Send messages to car in quanta
- Take in message input over period of time/ distance for a more accurate emulation of physics and smoother appearance of driving

**Comment by alrapal** [comment]
Hey ! We were thinking about that the other day and thought about maybe adapting the slowDown smoothly method to make a "changeSpeed" smoothly method, that might be an idea also.
The only problem with that one, is that the car still need to be able to break in emergency or react to side etc while adjusting the speed. =) 

We could also look from the front end and send the message progressively to the car (like a current speed to new speed with a certain % until it reaches a certain value close to the new speed. But by taking it from the receiving/car side it might conflict with the accident prevention part since it will block the loop while adjusting the speed. 
I don't know if that is clear, let me know if you want to discuss this possibility =)

**Comment by juliavankirk** [comment]
> We could also look from the front end and send the message progressively to the car (like a current speed to new speed with a certain % until it reaches a certain value close to the new speed. But by taking it from the receiving/car side it might conflict with the accident prevention part since it will block the loop while adjusting the speed.

**Comment by juliavankirk** [comment]
> We could also look from the front end and send the message progressively to the car (like a current speed to new speed with a certain % until it reaches a certain value close to the new speed. But by taking it from the receiving/car side it might conflict with the accident prevention part since it will block the loop while adjusting the speed.

I think you were on track with decreasing the percentage to handle delta speed and delta angle. For speed, we can send messages every 5 seconds/ 1 meter (whatever unit) travelled or so; for direction, we can send messages every 5 seconds. I think this all needs to be handled in the backend where messages are being received, and not client side though, as the car's state itself is being changed and it would be more accurate. Also would be smoother in the event of message drops, but idk :)

**Comment by alrapal** [comment]
> > We could also look from the front end and send the message progressively to the car (like a current speed to new speed with a certain % until it reaches a certain value close to the new speed. But by taking it from the receiving/car side it might conflict with the accident prevention part since it will block the loop while adjusting the speed.
> 
> I think you were on track with decreasing the percentage to handle delta speed and delta angle. For speed, we can send messages every 5 seconds/ 1 meter (whatever unit) travelled or so; for direction, we can send messages every 5 seconds. I think this all needs to be handled in the backend where messages are being received, and not client side though, as the car's state itself is being changed and it would be more accurate. Also would be smoother in the event of message drops, but idk :)

I agree, the backend is definitely more suitable to handle that part. I am just not sure it can be done without blocking the loop (it might be possible, we just have to explore that possibility). If you want, we can have a look at that together =)

**Comment by iachella** [comment]
Refer to Connectivity loss & safety  branch for suggested fixes. The issue will be closed after some finalizing and documentation about it.
